// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.887
package auth

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"templ_workout/internals/auth"
	"templ_workout/views/layouts"
)

func Register() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<script src=\"/assets/js/auth.js\" defer></script> <div class=\"hero min-h-screen\" style=\"background-image: url(/assets/images/213.webp);\"><div class=\"hero-overlay\"></div><div class=\"hero-content text-neutral-content text-center w-full\"><div class=\"card bg-base-100 w-full max-w-sm shrink-0 shadow-2xl mx-auto mt-[20%] translate-y-[-50%]\"><form method=\"POST\" action=\"/register\" onsubmit=\"register_submit(event)\" class=\"card-body\"><h1>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(auth.GetUserEmailFromContext(ctx))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/auth/register.templ`, Line: 16, Col: 45}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</h1><h1>Daa</h1><h2 class=\"text-3xl font-bold\">Register</h2><fieldset class=\"fieldset\"><label class=\"label\">Email</label> <input type=\"email\" name=\"email\" id=\"email\" class=\"input\" placeholder=\"Email\" required> <label class=\"label\">Name</label> <input type=\"text\" id=\"name\" name=\"name\" class=\"input\" placeholder=\"Name\" required> <label class=\"label\">Password</label> <input type=\"password\" id=\"password\" name=\"password\" class=\"input\" placeholder=\"Password\" required> <label class=\"label\">Confirm Password</label> <input type=\"password\" id=\"confirmPassword\" name=\"confirmPassword\" class=\"input\" placeholder=\"Confirm Password\" required><div class=\"flex gap-5 mt-4\"><a href=\"/login\" class=\"btn  btn-outline flex-1\">Login</a> <button type=\"submit\" class=\"btn btn-accent flex-1\">Register</button></div></fieldset></form></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layouts.App().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
